//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public option()
        {
            this.responses = new HashSet<respons>();
        }
    
        public int id { get; set; }
        public int question_id { get; set; }
        public string text { get; set; }
        public bool active { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<System.DateTime> deactivated_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respons> responses { get; set; }
        public virtual question question { get; set; }
    }
}
