//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respons
    {
        public int id { get; set; }
        public int question_id { get; set; }
        public int hospital_id { get; set; }
        public Nullable<int> option_id { get; set; }
        public string response_text { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    
        public virtual hospital hospital { get; set; }
        public virtual option option { get; set; }
        public virtual question question { get; set; }
    }
}
